// Code generated by "stringer -type=ProgressMethods"; DO NOT EDIT.

package domain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ALL-0]
	_ = x[ONLINE-1]
	_ = x[OFFLINE-2]
}

const _ProgressMethods_name = "ALLONLINEOFFLINE"

var _ProgressMethods_index = [...]uint8{0, 3, 9, 16}

func (i ProgressMethods) String() string {
	if i < 0 || i >= ProgressMethods(len(_ProgressMethods_index)-1) {
		return "ProgressMethods(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ProgressMethods_name[_ProgressMethods_index[i]:_ProgressMethods_index[i+1]]
}
